non_intrusive = [
    "Sigh",
    "Mantra",
    "Humming",
    "Breathing",
    "Heart sounds, heartbeat",
    "Heart murmur",
    "Insect",
    "Buzz",
    "Percussion",
    "Gong",
    "Wind",
    "Rustling leaves",
    "Rain",
    "Raindrop",
    "Rain on surface",
    "Vehicle",
    "Motor vehicle (road)",
    "Car",
    "Car passing by",
    "Truck",
    "Bus",
    "Traffic noise, roadway noise",
    "Bicycle",
    "Skateboard",
    "Engine",
    "Light engine (high frequency)",
    "Medium engine (mid frequency)",
    "Heavy engine (low frequency)",
    "Clock",
    "Tick",
    "Tick-tock",
    "Mechanical fan",
    "Air conditioning",
    "Whoosh, swoosh, swish",
    "Hum",
    "Silence",
    "Sine wave",
    "Inside, small room",
    "Inside, large room or hall",
    "Static",
    "Mains hum",
    "White noise",
    "Pink noise",
    "Throbbing",
    "Sound effect",
    "Busy signal",
    "Wind chime",
    "Chime",
    "Tuning fork",
    "Owl",
    "Musical instrument",
    "Music",
    "Synthesizer",
    "Sidetone",
    "Singing bowl",
    "Writing",
    "Harmonic",
    "Moo",
    "Mouse",
    "Chirp tone",
    "Fly, housefly",
]
